---
- name: Converge
  hosts: all
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: Copy something to test use of synchronize module
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /tmp/hosts-from-controller
        mode: '0666'
- name: "Include test.myrole"
  ansible.builtin.import_playbook: ../../../../playbooks/hello_world.yml
